<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\Customer\AddressController;
use App\Http\Controllers\Customer\BrowseController;
use App\Http\Controllers\Customer\CartController;
use App\Http\Controllers\Customer\ComplaintController;
use App\Http\Controllers\Customer\OrderController;
use App\Http\Controllers\Customer\ProfileController;
use App\Http\Controllers\Customer\ReviewController;
use App\Http\Controllers\Vendor\VendorProfileController;
use App\Http\Controllers\Vendor\RestaurantController;
use App\Http\Controllers\Vendor\FoodItemController;
use App\Http\Controllers\Vendor\VendorOrderController;
use App\Http\Controllers\Vendor\VendorDashboardController;
use App\Http\Controllers\Admin\AdminBannerController;
use App\Http\Controllers\Admin\AdminCategoryController;
use App\Http\Controllers\Admin\AdminComplaintController;
use App\Http\Controllers\Admin\AdminCouponController;
use App\Http\Controllers\Admin\AdminCustomerController;
use App\Http\Controllers\Admin\AdminDashboardController;
use App\Http\Controllers\Admin\AdminDeliveryController;
use App\Http\Controllers\Admin\AdminFoodController;
use App\Http\Controllers\Admin\AdminOrderController;
use App\Http\Controllers\Admin\AdminPaymentController;
use App\Http\Controllers\Admin\AdminReportController;
use App\Http\Controllers\Admin\AdminRestaurantController;
use App\Http\Controllers\Admin\AdminVendorController;
use App\Http\Controllers\Delivery\DeliveryEarningController;
use App\Http\Controllers\Delivery\DeliveryOrderController;
use App\Http\Controllers\Delivery\DeliveryProfileController;
use Illuminate\Support\Facades\Route;

Route::prefix('public')->group(function (): void {
    Route::get('restaurants', [\App\Http\Controllers\Api\PublicController::class, 'restaurantsIndex']);
    Route::get('restaurants/{id}', [\App\Http\Controllers\Api\PublicController::class, 'restaurantsShow']);
    Route::get('restaurants/{id}/menu', [\App\Http\Controllers\Api\PublicController::class, 'restaurantsMenu']);
    Route::get('foods', [\App\Http\Controllers\Api\PublicController::class, 'foodsIndex']);
    Route::get('foods/{id}', [\App\Http\Controllers\Api\PublicController::class, 'foodsShow']);
    Route::get('categories', [\App\Http\Controllers\Api\PublicController::class, 'categoriesIndex']);
});

Route::get('restaurants', [BrowseController::class, 'restaurantsIndex']);
Route::get('restaurants/{id}', [BrowseController::class, 'restaurantsShow']);
Route::get('restaurants/{id}/menu', [BrowseController::class, 'restaurantsMenu']);
Route::get('foods', [BrowseController::class, 'foodsIndex']);
Route::get('foods/{id}', [BrowseController::class, 'foodsShow']);
Route::get('categories', [BrowseController::class, 'categoriesIndex']);

Route::prefix('auth')->group(function (): void {
    Route::post('register', [AuthController::class, 'register']);
    Route::post('login', [AuthController::class, 'login']);
    Route::post('logout', [AuthController::class, 'logout'])->middleware('auth:sanctum');
    Route::get('me', [AuthController::class, 'me'])->middleware('auth:sanctum');
    Route::put('profile', [AuthController::class, 'profile'])->middleware('auth:sanctum');
    Route::post('change-password', [AuthController::class, 'changePassword'])->middleware('auth:sanctum');
});

Route::middleware(['auth:sanctum', 'account.active'])->group(function (): void {
    Route::get('notifications', [NotificationController::class, 'index']);
    Route::patch('notifications/{id}/read', [NotificationController::class, 'read']);
    Route::patch('notifications/read-all', [NotificationController::class, 'readAll']);

    Route::prefix('customer')->middleware('role:customer')->group(function (): void {
        Route::get('profile', [ProfileController::class, 'profile']);
        Route::put('profile', [ProfileController::class, 'profileUpdate']);
        Route::get('addresses', [AddressController::class, 'addressesIndex']);
        Route::post('addresses', [AddressController::class, 'addressesStore']);
        Route::put('addresses/{id}', [AddressController::class, 'addressesUpdate']);
        Route::delete('addresses/{id}', [AddressController::class, 'addressesDestroy']);
        Route::patch('addresses/{id}/default', [AddressController::class, 'addressesDefault']);
        Route::get('restaurants', [BrowseController::class, 'restaurantsIndex']);
        Route::get('restaurants/{id}', [BrowseController::class, 'restaurantsShow']);
        Route::get('restaurants/{id}/menu', [BrowseController::class, 'restaurantsMenu']);
        Route::get('foods', [BrowseController::class, 'foodsIndex']);
        Route::get('foods/{id}', [BrowseController::class, 'foodsShow']);
        Route::get('categories', [BrowseController::class, 'categoriesIndex']);
        Route::get('cart', [CartController::class, 'cartShow']);
        Route::get('cart/summary', [CartController::class, 'cartSummary']);
        Route::post('cart/items', [CartController::class, 'cartStore']);
        Route::put('cart/items/{id}', [CartController::class, 'cartUpdate']);
        Route::delete('cart/items/{id}', [CartController::class, 'cartDestroy']);
        Route::delete('cart/clear', [CartController::class, 'cartClear']);
        Route::post('cart/apply-coupon', [CartController::class, 'cartApplyCoupon']);
        Route::post('checkout', [OrderController::class, 'checkout']);
        Route::get('orders', [OrderController::class, 'ordersIndex']);
        Route::get('orders/{id}', [OrderController::class, 'ordersShow']);
        Route::get('orders/{id}/track', [OrderController::class, 'ordersTrack']);
        Route::post('orders/{id}/cancel', [OrderController::class, 'ordersCancel']);
        Route::post('orders/{id}/reorder', [OrderController::class, 'ordersReorder']);
        Route::get('orders/{id}/invoice', [OrderController::class, 'ordersInvoice']);
        Route::get('reviews', [ReviewController::class, 'reviewsIndex']);
        Route::post('reviews', [ReviewController::class, 'reviewsStore']);
        Route::put('reviews/{id}', [ReviewController::class, 'reviewsUpdate']);
        Route::delete('reviews/{id}', [ReviewController::class, 'reviewsDestroy']);
        Route::get('complaints', [ComplaintController::class, 'complaintsIndex']);
        Route::post('complaints', [ComplaintController::class, 'complaintsStore']);
    });

    Route::prefix('vendor')->middleware('role:vendor')->group(function (): void {
        Route::get('profile', [VendorProfileController::class, 'profile']);
        Route::put('profile', [VendorProfileController::class, 'profileUpdate']);
        Route::get('restaurant', [RestaurantController::class, 'restaurantShow']);
        Route::post('restaurant', [RestaurantController::class, 'restaurantStore']);
        Route::put('restaurant', [RestaurantController::class, 'restaurantUpdate']);
        Route::post('restaurant/documents', [RestaurantController::class, 'documentsStore']);
        Route::get('food-items', [FoodItemController::class, 'foodsIndex']);
        Route::post('food-items', [FoodItemController::class, 'foodsStore']);
        Route::get('food-items/{id}', [FoodItemController::class, 'foodsShow']);
        Route::put('food-items/{id}', [FoodItemController::class, 'foodsUpdate']);
        Route::delete('food-items/{id}', [FoodItemController::class, 'foodsDestroy']);
        Route::patch('food-items/{id}/stock', [FoodItemController::class, 'foodsStock']);
        Route::patch('food-items/{id}/status', [FoodItemController::class, 'foodsStatus']);
        Route::get('orders', [VendorOrderController::class, 'ordersIndex']);
        Route::get('orders/{id}', [VendorOrderController::class, 'ordersShow']);
        Route::post('orders/{id}/accept', [VendorOrderController::class, 'ordersAccept']);
        Route::post('orders/{id}/reject', [VendorOrderController::class, 'ordersReject']);
        Route::patch('orders/{id}/status', [VendorOrderController::class, 'ordersStatus']);
        Route::get('orders/{id}/invoice', [VendorOrderController::class, 'ordersInvoice']);
        Route::get('dashboard', [VendorDashboardController::class, 'dashboard']);
        Route::get('reports/sales', [VendorDashboardController::class, 'reportsSales']);
        Route::get('reports/best-selling', [VendorDashboardController::class, 'reportsBestSelling']);
        Route::get('reviews', [VendorDashboardController::class, 'reviewsIndex']);
        Route::get('payouts', [VendorDashboardController::class, 'payoutsIndex']);
    });

    Route::prefix('admin')->middleware('role:admin')->group(function (): void {
        Route::get('dashboard', [AdminDashboardController::class, 'dashboard']);
        Route::get('customers', [AdminCustomerController::class, 'customersIndex']);
        Route::get('customers/{id}', [AdminCustomerController::class, 'customersShow']);
        Route::patch('customers/{id}/block', [AdminCustomerController::class, 'customersBlock']);
        Route::patch('customers/{id}/unblock', [AdminCustomerController::class, 'customersUnblock']);
        Route::get('customers/{id}/orders', [AdminCustomerController::class, 'customersOrders']);
        Route::get('vendors', [AdminVendorController::class, 'vendorsIndex']);
        Route::get('vendors/pending', [AdminVendorController::class, 'vendorsPending']);
        Route::get('vendors/{id}', [AdminVendorController::class, 'vendorsShow']);
        Route::post('vendors/{id}/approve', [AdminVendorController::class, 'vendorsApprove']);
        Route::post('vendors/{id}/reject', [AdminVendorController::class, 'vendorsReject']);
        Route::patch('vendors/{id}/suspend', [AdminVendorController::class, 'vendorsSuspend']);
        Route::patch('vendors/{id}/commission', [AdminVendorController::class, 'vendorsCommission']);
        Route::delete('vendors/{id}', [AdminVendorController::class, 'vendorsDestroy']);
        Route::patch('vendors/{id}/verify-documents', [AdminVendorController::class, 'vendorsVerifyDocuments']);
        Route::get('restaurants', [AdminRestaurantController::class, 'restaurantsIndex']);
        Route::get('restaurants/{id}', [AdminRestaurantController::class, 'restaurantsShow']);
        Route::patch('restaurants/{id}/suspend', [AdminRestaurantController::class, 'restaurantsSuspend']);
        Route::patch('restaurants/{id}/activate', [AdminRestaurantController::class, 'restaurantsActivate']);
        Route::put('restaurants/{id}', [AdminRestaurantController::class, 'restaurantsUpdate']);
        Route::delete('restaurants/{id}', [AdminRestaurantController::class, 'restaurantsDestroy']);
        Route::get('delivery-partners', [AdminDeliveryController::class, 'deliveryPartnersIndex']);
        Route::get('delivery-partners/pending', [AdminDeliveryController::class, 'deliveryPartnersPending']);
        Route::get('delivery-partners/available', [AdminDeliveryController::class, 'deliveryPartnersAvailable']);
        Route::get('delivery-partners/{id}', [AdminDeliveryController::class, 'deliveryPartnersShow']);
        Route::post('delivery-partners/{id}/approve', [AdminDeliveryController::class, 'deliveryPartnersApprove']);
        Route::post('delivery-partners/{id}/reject', [AdminDeliveryController::class, 'deliveryPartnersReject']);
        Route::patch('delivery-partners/{id}/suspend', [AdminDeliveryController::class, 'deliveryPartnersSuspend']);
        Route::get('delivery-requests', [AdminDeliveryController::class, 'deliveryRequestsIndex']);
        Route::get('categories', [AdminCategoryController::class, 'categoriesIndex']);
        Route::post('categories', [AdminCategoryController::class, 'categoriesStore']);
        Route::put('categories/{id}', [AdminCategoryController::class, 'categoriesUpdate']);
        Route::delete('categories/{id}', [AdminCategoryController::class, 'categoriesDestroy']);
        Route::get('food-items', [AdminFoodController::class, 'foodItemsIndex']);
        Route::get('food-items/{id}', [AdminFoodController::class, 'foodItemsShow']);
        Route::patch('food-items/{id}/disable', [AdminFoodController::class, 'foodItemsDisable']);
        Route::patch('food-items/{id}/enable', [AdminFoodController::class, 'foodItemsEnable']);
        Route::delete('food-items/{id}', [AdminFoodController::class, 'foodItemsDestroy']);
        Route::get('banners', [AdminBannerController::class, 'bannersIndex']);
        Route::post('banners', [AdminBannerController::class, 'bannersStore']);
        Route::put('banners/{id}', [AdminBannerController::class, 'bannersUpdate']);
        Route::delete('banners/{id}', [AdminBannerController::class, 'bannersDestroy']);
        Route::patch('banners/{id}/status', [AdminBannerController::class, 'bannersStatus']);
        Route::get('orders', [AdminOrderController::class, 'ordersIndex']);
        Route::get('orders/{id}', [AdminOrderController::class, 'ordersShow']);
        Route::get('orders/{id}/track', [AdminOrderController::class, 'ordersTrack']);
        Route::post('orders/{id}/cancel', [AdminOrderController::class, 'ordersCancel']);
        Route::post('orders/{id}/refund', [AdminOrderController::class, 'ordersRefund']);
        Route::get('coupons', [AdminCouponController::class, 'couponsIndex']);
        Route::post('coupons', [AdminCouponController::class, 'couponsStore']);
        Route::put('coupons/{id}', [AdminCouponController::class, 'couponsUpdate']);
        Route::delete('coupons/{id}', [AdminCouponController::class, 'couponsDestroy']);
        Route::patch('coupons/{id}/status', [AdminCouponController::class, 'couponsStatus']);
        Route::get('payments', [AdminPaymentController::class, 'paymentsIndex']);
        Route::get('commissions', [AdminPaymentController::class, 'commissionsIndex']);
        Route::get('vendor-payouts', [AdminPaymentController::class, 'vendorPayoutsIndex']);
        Route::post('vendor-payouts', [AdminPaymentController::class, 'vendorPayoutsStore']);
        Route::patch('vendor-payouts/{id}/status', [AdminPaymentController::class, 'vendorPayoutsStatus']);
        Route::get('complaints', [AdminComplaintController::class, 'complaintsIndex']);
        Route::get('complaints/{id}', [AdminComplaintController::class, 'complaintsShow']);
        Route::post('complaints/{id}/reply', [AdminComplaintController::class, 'complaintsReply']);
        Route::patch('complaints/{id}/status', [AdminComplaintController::class, 'complaintsStatus']);
        Route::get('reports/daily-sales', [AdminReportController::class, 'reportsDailySales']);
        Route::get('reports/monthly-revenue', [AdminReportController::class, 'reportsMonthlyRevenue']);
        Route::get('reports/vendor-sales', [AdminReportController::class, 'reportsVendorSales']);
        Route::get('reports/commission', [AdminReportController::class, 'reportsCommission']);
        Route::get('reports/cancellations', [AdminReportController::class, 'reportsCancellations']);
        Route::get('reports/payments', [AdminReportController::class, 'reportsPayments']);
    });

    Route::prefix('delivery')->middleware('role:delivery_partner')->group(function (): void {
        Route::get('profile', [DeliveryProfileController::class, 'profile']);
        Route::put('profile', [DeliveryProfileController::class, 'profileUpdate']);
        Route::patch('profile/availability', [DeliveryProfileController::class, 'availabilityUpdate']);
        Route::post('kyc', [DeliveryProfileController::class, 'kycStore']);
        Route::get('available-requests', [DeliveryOrderController::class, 'availableRequestsIndex']);
        Route::get('available-requests/{id}', [DeliveryOrderController::class, 'availableRequestsShow']);
        Route::post('available-requests/{id}/accept', [DeliveryOrderController::class, 'availableRequestsAccept']);
        Route::get('orders', [DeliveryOrderController::class, 'ordersIndex']);
        Route::get('orders/{id}', [DeliveryOrderController::class, 'ordersShow']);
        Route::post('orders/{id}/accept', [DeliveryOrderController::class, 'ordersAccept']);
        Route::patch('orders/{id}/pickup', [DeliveryOrderController::class, 'ordersPickup']);
        Route::patch('orders/{id}/status', [DeliveryOrderController::class, 'ordersStatus']);
        Route::patch('orders/{id}/delivered', [DeliveryOrderController::class, 'ordersDelivered']);
        Route::get('history', [DeliveryOrderController::class, 'historyIndex']);
        Route::get('earnings', [DeliveryEarningController::class, 'earningsIndex']);
        Route::get('ratings', [DeliveryEarningController::class, 'ratingsIndex']);
    });
});